### ISSUE TITLE
Week 1 MoM

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/522-workflows-group-18#5]
Status as of Wed Nov 8
---

**Milestone 1 Task Summary:**
*see specific issues for to do's and assignments*
- [ ] Draft a team work contract 
- [ ] Set-up a public GitHub repository
- [ ] Create an appropriate file and directory structure for a data analysis project 
--> @atabak-alishiri CONTRIBUTING.md, LICENSE.md
--> @rbouwer populate CODE_OF_CONDUCT.md and set up directory structure (data/, <analysis>.ipynb [give it a meaningful name!])
- [ ] Add the data analysis as a literate code document --> @salva-u 
- [ ] Ensure the computation environment reproducible through a virtual environment (e.g., conda or renv) - hint do this as you create the analysis, don’t wait until the end! --> @farrandi to populate environment file - will add to directory once created

**Summary of Meeting:**
- Discussed the communications methods and completed the work contract
- Discussed the domain of the research question 
- Selection of appropriate dataset (within language domain): https://osf.io/g72pq (from paper: https://www.sciencedirect.com/science/article/pii/S0010027718300994)
- Pending research question selection (conversation in comments below), will complete (unchecked) steps 3, 4, 5 (above)
- Meet tomorrow to set up project board for action item tracking
- Everyone to update the readme as we go - will touch base on Thursday Nov 18

**Comment by salva-u** [comment]
Some suggestions for the chosen dataset that we could solve with regression analysis
1. Investigate if psychological and health factors, such as dyslexia and psychiatric conditions, have a significant impact on English proficiency.
2. Explore the impact of factors like the age at which participants started learning English and the number of years spent in English-speaking countries on language proficiency.
3. Analyze the differences in English proficiency between multilingual participants and monolingual participants and identify any benefits or challenges associated with multilingualism

**Comment by atabak-alishiri** [comment]
Here is my suggestion based on the dataset:

**Predicting proficiency based on age of acquisition, years in an English-speaking country, and education level:**

- Features: We probably need Eng_start, Eng_country_yrs, and education as features.
- Target: We can use correct as the target variable for proficiency.
- Model: Probably regression models or classification models if we want to bin the correct column into classes (Beginner, Intermediate, etc.)

**Comment by salva-u** [comment]
data dictionary: https://osf.io/pyb8s/wiki/home/
data: https://osf.io/g72pq
paper: https://www.sciencedirect.com/science/article/pii/S0010027718300994

**Comment by atabak-alishiri** [comment]
We decided to include 8 columns in our analysis this week:
- **age, dyslexia, psychiatric, eng_start, education, nat_english, prime_english, speaker_cat**
- target is **correct**

**Comment by salva-u** [comment]
Changed the research question based on Tiffany's feedback; to start off the research question now is: Can we predict an individual's English proficiency score based on factors such as age, education, and language background?
